return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["3"] = {
                ActionType              = 'Spell',
                Id                      = 112,
                Macro                   = T{
                    "/ma \"Flash\" <t>",
                },
                Label                   = "Flash",
                Image                   = "spells/112.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["0"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/echo DONE!!!",
                },
                Label                   = "Attack",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};