require('common');

local settings = T{ };
settings["Config_Window_Visible"] = T{ };
settings["XP_Window_Visible"] = T{ };
settings["Parse_Window_Visible"] = T{ };
settings["Report_Window_Visible"] = T{ };
settings["Focus_Window_Visible"] = T{ };
settings["Blog_Window_Visible"] = T{ };
settings["Report_Y"] = 100;
settings["Y_Pos"] = 100;
settings["Parse_X"] = 100;
settings["Active_Window"] = "Parse";
settings["Config_Window_Visible"][1] = false;
settings["XP_Window_Visible"][1] = false;
settings["Parse_Window_Visible"][1] = true;
settings["Alpha"] = 1;
settings["Screenshot_Y"] = 100;
settings["X_Pos"] = 100;
settings["Focus_Y"] = 100;
settings["Hub_Y"] = 100;
settings["Parse_Y"] = 100;
settings["Screenshot_X"] = 100;
settings["Focus_X"] = 100;
settings["Hub_X"] = 100;
settings["Report_Window_Visible"][1] = false;
settings["Window_Scaling"] = 1;
settings["Focus_Window_Visible"][1] = false;
settings["Blog_X"] = 100;
settings["Blog_Y"] = 100;
settings["Show_Mouse"] = false;
settings["XP_Y"] = 100;
settings["Report_X"] = 100;
settings["Show_Title"] = false;
settings["XP_X"] = 100;
settings["Style"] = 0;
settings["Config_X"] = 100;
settings["Blog_Window_Visible"][1] = false;
settings["Config_Y"] = 100;
settings["Multi_Window"] = false;

return settings;
