return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Spell',
                Id                      = 156,
                Macro                   = T{
                    "/ma \"Aero III\" <t>",
                },
                Label                   = "Aero",
                Image                   = "spells2/blm/aero.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!9"] = {
                ActionType              = 'Spell',
                Id                      = 273,
                Macro                   = T{
                    "/ma \"Sleepga\" <t>",
                },
                Label                   = "Sleepga",
                Image                   = "spells2/blm/sleepga.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["5"] = {
                ActionType              = 'Spell',
                Id                      = 171,
                Macro                   = T{
                    "/ma \"Water III\" <t>",
                },
                Label                   = "Water",
                Image                   = "spells2/blm/water.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!5"] = {
                ActionType              = 'Spell',
                Id                      = 237,
                Macro                   = T{
                    "/ma \"Choke\" <t>",
                },
                Label                   = "Choke",
                Image                   = "spells2/blm/choke.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!6"] = {
                ActionType              = 'Spell',
                Id                      = 239,
                Macro                   = T{
                    "/ma \"Shock\" <t>",
                },
                Label                   = "Shock",
                Image                   = "spells2/blm/shock.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^7"] = {
                ActionType              = 'Spell',
                Id                      = 59,
                Macro                   = T{
                    "/ma \"Silence\" <t>",
                },
                Label                   = "Silence",
                Image                   = "spells2/whm/silence.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!4"] = {
                ActionType              = 'Spell',
                Id                      = 235,
                Macro                   = T{
                    "/ma \"Burn\" <t>",
                },
                Label                   = "Burn",
                Image                   = "spells2/blm/burn.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Spell',
                Id                      = 258,
                Macro                   = T{
                    "/ma \"Bind\" <t>",
                },
                Label                   = "Bind",
                Image                   = "spells2/blm/bind.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 587,
                Macro                   = T{
                    "/ja \"Elemental Seal\" <me>",
                },
                Label                   = "Elemental Seal",
                Image                   = "spells2/blm/seal.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["7"] = {
                ActionType              = 'Spell',
                Id                      = 252,
                Macro                   = T{
                    "/ma \"Stun\" <t>",
                },
                Label                   = "Stun",
                Image                   = "spells2/blm/stun.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^5"] = {
                ActionType              = 'Spell',
                Id                      = 199,
                Macro                   = T{
                    "/ma \"Waterga\" <t>",
                },
                Label                   = "Waterga",
                Image                   = "spells2/blm/waterga.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!8"] = {
                ActionType              = 'Spell',
                Id                      = 259,
                Macro                   = T{
                    "/ma \"Sleep II\" <t>",
                },
                Label                   = "Sleep II",
                Image                   = "spells2/blm/sleep2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^8"] = {
                ActionType              = 'Spell',
                Id                      = 216,
                Macro                   = T{
                    "/ma \"Gravity\" <t>",
                },
                Label                   = "Gravity",
                Image                   = "spells2/rdm/grav.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 196,
                Macro                   = T{
                    "/ma \"Thundaga III\" <t>",
                },
                Label                   = "Thundaga III",
                Image                   = "spells2/blm/thundaga.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["8"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/echo done",
                },
                Label                   = "synth",
                Image                   = "misc/synth.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Spell',
                Id                      = 167,
                Macro                   = T{
                    "/ma \"Thunder IV\" <t>",
                },
                Label                   = "Thunder",
                Image                   = "spells2/blm/thunder.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 181,
                Macro                   = T{
                    "/ma \"Blizzaga III\" <t>",
                },
                Label                   = "Blizzaga",
                Image                   = "spells2/blm/blizzaga.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["6"] = {
                ActionType              = 'Spell',
                Id                      = 161,
                Macro                   = T{
                    "/ma \"Stone III\" <t>",
                },
                Label                   = "Stone",
                Image                   = "spells2/blm/stone.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^4"] = {
                ActionType              = 'Spell',
                Id                      = 185,
                Macro                   = T{
                    "/ma \"Aeroga II\" <t>",
                },
                Label                   = "Aeroga",
                Image                   = "spells2/blm/aeroga.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Spell',
                Id                      = 176,
                Macro                   = T{
                    "/ma \"Firaga III\" <t>",
                },
                Label                   = "Firaga",
                Image                   = "spells2/blm/firaga.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 245,
                Macro                   = T{
                    "/ma \"Drain\" <t>",
                },
                Label                   = "Drain",
                Image                   = "spells2//blm/drain.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 247,
                Macro                   = T{
                    "/ma \"Aspir\" <t>",
                },
                Label                   = "Aspir",
                Image                   = "spells2/blm/aspir.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Spell',
                Id                      = 147,
                Macro                   = T{
                    "/ma \"Fire IV\" <t>",
                },
                Label                   = "Fire",
                Image                   = "spells2/blm/fire.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 274,
                Macro                   = T{
                    "/ma \"Sleepga II\" <t>",
                },
                Label                   = "Sleepga II",
                Image                   = "spells2/blm/sleepga2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Spell',
                Id                      = 151,
                Macro                   = T{
                    "/ma \"Blizzard III\" <t>",
                },
                Label                   = "Blizzard",
                Image                   = "spells2/blm/bliz.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!7"] = {
                ActionType              = 'Spell',
                Id                      = 253,
                Macro                   = T{
                    "/ma \"Sleep\" <t>",
                },
                Label                   = "Sleep",
                Image                   = "spells2/blm/sleep.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!3"] = {
                ActionType              = 'Spell',
                Id                      = 231,
                Macro                   = T{
                    "/ma \"Bio II\" <t>",
                },
                Label                   = "Bio II",
                Image                   = "spells2/blm/bio.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^6"] = {
                ActionType              = 'Spell',
                Id                      = 190,
                Macro                   = T{
                    "/ma \"Stonega II\" <t>",
                },
                Label                   = "Stonega",
                Image                   = "spells2/blm/stonega.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};