return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!7"] = {
                ActionType              = 'Spell',
                Id                      = 462,
                Macro                   = T{
                    "/ma \"Magic Finale\" <t>",
                },
                Label                   = "Magic Finale",
                Image                   = "spells/462.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Spell',
                Id                      = 394,
                Macro                   = T{
                    "/equip range \"Cornette +1\"",
                    "/ma \"Valor Minuet\" <me>",
                },
                Label                   = "Minuet",
                Image                   = "spells/394.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["0"] = {
                ActionType              = 'Spell',
                Id                      = 460,
                Macro                   = T{
                    "/equip range \"Piccolo +1\"",
                    "/ma \"Light Threnody\" <t>",
                },
                Label                   = "Light Threnody",
                Image                   = "spells/460.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["9"] = {
                ActionType              = 'Spell',
                Id                      = 369,
                Macro                   = T{
                    "/equip range \"Flute +1\"",
                    "/ma \"Foe Requiem II\" <t>",
                },
                Label                   = "Foe Requiem II",
                Image                   = "spells/369.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Spell',
                Id                      = 378,
                Macro                   = T{
                    "/ma \"Army's Paeon\" <me>",
                },
                Label                   = "Army's Paeon",
                Image                   = "spells/378.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!9"] = {
                ActionType              = 'Spell',
                Id                      = 376,
                Macro                   = T{
                    "/ma \"Horde Lullaby\" <t>",
                },
                Label                   = "Horde Lullaby",
                Image                   = "spells/376.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Spell',
                Id                      = 395,
                Macro                   = T{
                    "/equip range \"Cornette +1\"",
                    "/ma \"Valor Minuet II\" <me>",
                },
                Label                   = "Valor Minuet II",
                Image                   = "spells/395.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/equip range \"Piccolo +1\"",
                    "/equip range \"Cornette +1\"",
                },
                Label                   = "Swap",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^4"] = {
                ActionType              = 'Spell',
                Id                      = 379,
                Macro                   = T{
                    "/ma \"Army's Paeon II\" <me>",
                },
                Label                   = "Army's Paeon II",
                Image                   = "spells/379.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Spell',
                Id                      = 399,
                Macro                   = T{
                    "/ma \"Sword Madrigal\" <me>",
                },
                Label                   = "Sword Madrigal",
                Image                   = "spells/399.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 537,
                Macro                   = T{
                    "/ja \"Soul Voice\" <me>",
                },
                Label                   = "Soul Voice",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!8"] = {
                ActionType              = 'Spell',
                Id                      = 463,
                Macro                   = T{
                    "/ma \"Foe Lullaby\" <t>",
                },
                Label                   = "Foe Lullaby",
                Image                   = "spells/463.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells/353.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 419,
                Macro                   = T{
                    "/ma \"Advancing March\" <me>",
                },
                Label                   = "Advancing March",
                Image                   = "spells/419.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 386,
                Macro                   = T{
                    "/ma \"Mage's Ballad\" <me>",
                },
                Label                   = "Mage's Ballad",
                Image                   = "spells/386.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};