return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities2/bst/stay.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^7"] = {
                ActionType              = 'Ability',
                Id                      = 557,
                Macro                   = T{
                    "/ja \"Mug\" <t>",
                },
                Label                   = "Mug",
                Image                   = "abilities2/thf/mug.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["5"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Ichi",
                Image                   = "spells2/nin/ichi.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^8"] = {
                ActionType              = 'Ability',
                Id                      = 554,
                Macro                   = T{
                    "/ja \"Flee\" <me>",
                },
                Label                   = "Flee",
                Image                   = "abilities2/thf/flee.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Ability',
                Id                      = 597,
                Macro                   = T{
                    "/ja \"Call Beast\" <me>",
                },
                Label                   = "Call Beast",
                Image                   = "abilities2/bst/loyalty.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["7"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/target Izual",
                    "/assist Izual",
                    "/wait 1",
                    "/attack <t>",
                    "/wait 2",
                    "/follow",
                    "/ja fight <t>",
                    "/wait 5",
                    "/bstpet 2 <me>",
                },
                Label                   = "Assist",
                Image                   = "misc/assist.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!4"] = {
                ActionType              = 'Spell',
                Id                      = 143,
                Macro                   = T{
                    "/ma \"Erase\" <me>",
                },
                Label                   = "Erase",
                Image                   = "spells2/whm/erase.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^1"] = {
                ActionType              = 'Ability',
                Id                      = 1201,
                Macro                   = T{
                    "/ja \"Lamb Chop\" <me>",
                },
                Label                   = "Chop",
                Image                   = "abilities2/bst/chop.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["0"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/equip ammo \"S. Herbal Broth\"",
                },
                Label                   = "Sheep",
                Image                   = "abilities2/bst/sheep.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 536,
                Macro                   = T{
                    "/ja \"Familiar\" <me>",
                },
                Label                   = "Familiar",
                Image                   = "abilities2/bst/familiar.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["8"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lac set mp",
                    "/wait 1",
                    "/lac disable",
                },
                Label                   = "MP",
                Image                   = "misc/gear.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 69,
                Macro                   = T{
                    "/ws \"Rampage\" <t>",
                },
                Label                   = "Rampage",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities2/bst/fight.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lac set Idle",
                    "/wait 1",
                    "/lac disable",
                    "/wait 10",
                    "/lac enable",
                },
                Label                   = "-DMG",
                Image                   = "misc/gear.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities2/bst/charm.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^2"] = {
                ActionType              = 'Ability',
                Id                      = 590,
                Macro                   = T{
                    "/ja \"Reward\" <me>",
                },
                Label                   = "Reward",
                Image                   = "abilities2/bst/reward.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 24,
                Macro                   = T{
                    "/ma \"Dia II\" <t>",
                },
                Label                   = "Dia II",
                Image                   = "spells2/whm/dia.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^4"] = {
                ActionType              = 'Ability',
                Id                      = 566,
                Macro                   = T{
                    "/ja \"Tame\" <t>",
                },
                Label                   = "Tame",
                Image                   = "abilities2/bst/tame.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 3,
                Macro                   = T{
                    "/ma \"Cure III\" <me>",
                },
                Label                   = "Cure III",
                Image                   = "spells2/whm/cure_III.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 582,
                Macro                   = T{
                    "/ja \"Heel\" <me>",
                },
                Label                   = "Heel",
                Image                   = "abilities2/bst/heel.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["6"] = {
                ActionType              = 'Spell',
                Id                      = 339,
                Macro                   = T{
                    "/ma \"Utsusemi: Ni\" <me>",
                },
                Label                   = "Ni",
                Image                   = "spells2/nin/ni.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^5"] = {
                ActionType              = 'Ability',
                Id                      = 556,
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                },
                Label                   = "Sneak Attack",
                Image                   = "abilities2/thf/sa.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 354,
                Macro                   = T{
                    "/ma \"Tonko: Ni\" <me>",
                },
                Label                   = "Tonko",
                Image                   = "spells2/nin/tonko.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!3"] = {
                ActionType              = 'Spell',
                Id                      = 108,
                Macro                   = T{
                    "/ma \"Regen\" <me>",
                },
                Label                   = "Regen",
                Image                   = "spells2/whm/regen.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^6"] = {
                ActionType              = 'Ability',
                Id                      = 553,
                Macro                   = T{
                    "/ja \"Steal\" <t>",
                },
                Label                   = "Steal",
                Image                   = "abilities2/thf/steal.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};