return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities2/bst/stay.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!9"] = {
                ActionType              = 'Spell',
                Id                      = 137,
                Macro                   = T{
                    "/ma \"Sneak\" <me>",
                },
                Label                   = "Sneak",
                Image                   = "spells2/whm/sneak.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["5"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Ichi",
                Image                   = "spells2/nin/ichi.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!5"] = {
                ActionType              = 'Spell',
                Id                      = 126,
                Macro                   = T{
                    "/ma \"Protectra II\" <me>",
                },
                Label                   = "Protectra II",
                Image                   = "spells2/whm/protect.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!6"] = {
                ActionType              = 'Spell',
                Id                      = 131,
                Macro                   = T{
                    "/ma \"Shellra II\" <me>",
                },
                Label                   = "Shellra II",
                Image                   = "spells2/whm/shell.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Ability',
                Id                      = 899,
                Macro                   = T{
                    "/ja \"Bestial Loyalty\" <me>",
                },
                Label                   = "Bestial Loyalty",
                Image                   = "abilities2/bst/loyalty.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 536,
                Macro                   = T{
                    "/ja \"Familiar\" <me>",
                },
                Label                   = "Familiar",
                Image                   = "abilities2/bst/familiar.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^2"] = {
                ActionType              = 'Ability',
                Id                      = 590,
                Macro                   = T{
                    "/ja \"Reward\" <me>",
                },
                Label                   = "Reward",
                Image                   = "abilities2/bst/reward.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["0"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ctimers add Oats 0 1 0",
                },
                Label                   = "Timer",
                Image                   = "misc/timer.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!7"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/item \"Silent Oil\" <me>",
                },
                Label                   = "Oil",
                Image                   = "spells2/nin/oil.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities2/bst/fight.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 136,
                Macro                   = T{
                    "/ma \"Invisible\" <me>",
                },
                Label                   = "Invisible",
                Image                   = "spells2/whm/invis.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!8"] = {
                ActionType              = 'Spell',
                Id                      = 354,
                Macro                   = T{
                    "/ma \"Tonko: Ni\" <me>",
                },
                Label                   = "Tonko",
                Image                   = "spells2/nin/tonko.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/targetnpc",
                    "/item \"Pickaxe\" <t>",
                },
                Label                   = "Mine",
                Image                   = "misc/mine.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["6"] = {
                ActionType              = 'Spell',
                Id                      = 339,
                Macro                   = T{
                    "/ma \"Utsusemi: Ni\" <me>",
                },
                Label                   = "Ni",
                Image                   = "spells2/nin/ni.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 69,
                Macro                   = T{
                    "/ws \"Rampage\" <t>",
                },
                Label                   = "Rampage",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells2/whm/dia.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^4"] = {
                ActionType              = 'Ability',
                Id                      = 566,
                Macro                   = T{
                    "/ja \"Tame\" <t>",
                },
                Label                   = "Tame",
                Image                   = "abilities2/bst/tame.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 3,
                Macro                   = T{
                    "/ma \"Cure III\" <me>",
                },
                Label                   = "Cure III",
                Image                   = "spells2/whm/cure_III.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 582,
                Macro                   = T{
                    "/ja \"Heel\" <me>",
                },
                Label                   = "Heel",
                Image                   = "abilities2/bst/heel.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^1"] = {
                ActionType              = 'Ability',
                Id                      = 543,
                Macro                   = T{
                    "/ja \"Berserk\" <me>",
                },
                Label                   = "Berserk",
                Image                   = "abilities2/war/berserk.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^5"] = {
                ActionType              = 'Ability',
                Id                      = 544,
                Macro                   = T{
                    "/ja \"Warcry\" <me>",
                },
                Label                   = "Warcry",
                Image                   = "abilities2/war/warcry.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^3"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities2/bst/charm.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!3"] = {
                ActionType              = 'Spell',
                Id                      = 108,
                Macro                   = T{
                    "/ma \"Regen\" <me>",
                },
                Label                   = "Regen",
                Image                   = "spells2/whm/regen.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!4"] = {
                ActionType              = 'Spell',
                Id                      = 143,
                Macro                   = T{
                    "/ma \"Erase\" <me>",
                },
                Label                   = "Erase",
                Image                   = "spells2/whm/erase.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};