return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells2/whm/dia.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 578,
                Macro                   = T{
                    "/ja \"Jump\" <t>",
                },
                Label                   = "Jump",
                Image                   = "abilities2/drg/jump.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 112,
                Macro                   = T{
                    "/ws \"Double Thrust\" <t>",
                },
                Label                   = "Double Thrust",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 541,
                Macro                   = T{
                    "/ja \"Spirit Surge\" <me>",
                },
                Label                   = "Surge",
                Image                   = "abilities2/drg/surge.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
            },
        } },
    },
};