return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 245,
                Macro                   = T{
                    "/ma \"Drain\" <t>",
                },
                Label                   = "Drain",
                Image                   = "spells/245.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 48,
                Macro                   = T{
                    "/ws \"Hard Slash\" <t>",
                },
                Label                   = "Hard Slash",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities/69.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 230,
                Macro                   = T{
                    "/ma \"Bio\" <t>",
                },
                Label                   = "Bio",
                Image                   = "spells/230.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 220,
                Macro                   = T{
                    "/ma \"Poison\" <t>",
                },
                Label                   = "Poison",
                Image                   = "spells/220.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};