return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells2/nin/ichi.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["5"] = {
                ActionType              = 'Spell',
                Id                      = 339,
                Macro                   = T{
                    "/ma \"Utsusemi: Ni\" <me>",
                },
                Label                   = "Ni",
                Image                   = "spells2/nin/ni.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Ability',
                Id                      = 562,
                Macro                   = T{
                    "/ja \"Arcane Circle\" <me>",
                },
                Label                   = "Arcane Circle",
                Image                   = "abilities2/drk/arcane.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["7"] = {
                ActionType              = 'Spell',
                Id                      = 252,
                Macro                   = T{
                    "/ma \"Stun\" <t>",
                },
                Label                   = "Stun",
                Image                   = "spells2/blm/stun.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["0"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/drk movement",
                },
                Label                   = "Movement",
                Image                   = "misc/gear.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["8"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/drk idleset tank",
                },
                Label                   = "Tank",
                Image                   = "misc/gear.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 247,
                Macro                   = T{
                    "/ma \"Aspir\" <t>",
                },
                Label                   = "Aspir",
                Image                   = "spells2/blm/aspir.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/drk Enmity",
                },
                Label                   = "Enmity",
                Image                   = "misc/gear.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["6"] = {
                ActionType              = 'Ability',
                Id                      = 589,
                Macro                   = T{
                    "/ja \"Weapon Bash\" <t>",
                },
                Label                   = "Weapon Bash",
                Image                   = "abilities2/drk/wb.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Spell',
                Id                      = 258,
                Macro                   = T{
                    "/ma \"Bind\" <t>",
                },
                Label                   = "Bind",
                Image                   = "spells2/blm/bind.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 253,
                Macro                   = T{
                    "/ma \"Sleep\" <t>",
                },
                Label                   = "Sleep",
                Image                   = "spells2/blm/sleep.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 259,
                Macro                   = T{
                    "/ma \"Sleep II\" <t>",
                },
                Label                   = "Sleep II",
                Image                   = "spells2/blm/sleep2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 561,
                Macro                   = T{
                    "/ja \"Souleater\" <me>",
                },
                Label                   = "Souleater",
                Image                   = "abilities2/drk/souleater.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 245,
                Macro                   = T{
                    "/ma \"Drain\" <t>",
                },
                Label                   = "Drain",
                Image                   = "spells2/blm/drain.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 563,
                Macro                   = T{
                    "/ja \"Last Resort\" <me>",
                },
                Label                   = "Last Resort",
                Image                   = "abilities2/drk/lr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 103,
                Macro                   = T{
                    "/ws \"Cross Reaper\" <t>",
                },
                Label                   = "Cross",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 535,
                Macro                   = T{
                    "/ja \"Blood Weapon\" <me>",
                },
                Label                   = "Blood Weapon",
                Image                   = "abilities2/drk/bw.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
        { Name="sam", Bindings = T{
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 245,
                Macro                   = T{
                    "/ma \"Drain\" <t>",
                },
                Label                   = "Drain",
                Image                   = "spells2/blm/drain.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["6"] = {
                ActionType              = 'Ability',
                Id                      = 589,
                Macro                   = T{
                    "/ja \"Weapon Bash\" <t>",
                },
                Label                   = "Weapon Bash",
                Image                   = "abilities2/drk/wb.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 102,
                Macro                   = T{
                    "/ws \"Guillotine\" <t>",
                },
                Label                   = "Guillotine",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells2/nin/tonko.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!9"] = {
                ActionType              = 'Item',
                Id                      = 4165,
                Macro                   = T{
                    "/item \"Silent Oil\" <me>",
                },
                Label                   = "Silent Oil",
                Image                   = "ITEM:4165",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Spell',
                Id                      = 268,
                Macro                   = T{
                    "/ma \"Absorb-VIT\" <t>",
                },
                Label                   = "Absorb-VIT",
                Image                   = "spells/268.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 535,
                Macro                   = T{
                    "/ja \"Blood Weapon\" <me>",
                },
                Label                   = "Blood Weapon",
                Image                   = "abilities2/drk/bw.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Ability',
                Id                      = 686,
                Macro                   = T{
                    "/ja \"Seigan\" <me>",
                },
                Label                   = "Seigan",
                Image                   = "abilities2/sam/seigan.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Ability',
                Id                      = 685,
                Macro                   = T{
                    "/ja \"Hasso\" <me>",
                },
                Label                   = "Hasso",
                Image                   = "abilities2/sam/hasso.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Ability',
                Id                      = 562,
                Macro                   = T{
                    "/ja \"Arcane Circle\" <me>",
                },
                Label                   = "Arcane Circle",
                Image                   = "abilities2/drk/arcane.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 561,
                Macro                   = T{
                    "/ja \"Souleater\" <me>",
                },
                Label                   = "Souleater",
                Image                   = "abilities2/drk/souleater.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["7"] = {
                ActionType              = 'Spell',
                Id                      = 252,
                Macro                   = T{
                    "/ma \"Stun\" <t>",
                },
                Label                   = "Stun",
                Image                   = "spells2/blm/stun.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 563,
                Macro                   = T{
                    "/ja \"Last Resort\" <me>",
                },
                Label                   = "Last Resort",
                Image                   = "abilities2/drk/lr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 247,
                Macro                   = T{
                    "/ma \"Aspir\" <t>",
                },
                Label                   = "Aspir",
                Image                   = "spells2/blm/aspir.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!3"] = {
                ActionType              = 'Ability',
                Id                      = 575,
                Macro                   = T{
                    "/ja \"Meditate\" <me>",
                },
                Label                   = "Meditate",
                Image                   = "abilities2/sam/meditate.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!4"] = {
                ActionType              = 'Ability',
                Id                      = 574,
                Macro                   = T{
                    "/ja \"Third Eye\" <me>",
                },
                Label                   = "Third Eye",
                Image                   = "abilities2/sam/thirdeye.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
        { Name="thf", Bindings = T{
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 69,
                Macro                   = T{
                    "/ws \"Rampage\" <t>",
                },
                Label                   = "Rampage",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Ability',
                Id                      = 588,
                Macro                   = T{
                    "/ja \"Trick Attack\" <me>",
                },
                Label                   = "Trick Attack",
                Image                   = "abilities2/thf/TA.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 247,
                Macro                   = T{
                    "/ma \"Aspir\" <t>",
                },
                Label                   = "Aspir",
                Image                   = "spells2/blm/aspir.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^8"] = {
                ActionType              = 'Ability',
                Id                      = 554,
                Macro                   = T{
                    "/ja \"Flee\" <me>",
                },
                Label                   = "Flee",
                Image                   = "abilities2/thf/flee.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Spell',
                Id                      = 268,
                Macro                   = T{
                    "/ma \"Absorb-VIT\" <t>",
                },
                Label                   = "Absorb-VIT",
                Image                   = "spells/268.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["7"] = {
                ActionType              = 'Spell',
                Id                      = 252,
                Macro                   = T{
                    "/ma \"Stun\" <t>",
                },
                Label                   = "Stun",
                Image                   = "spells2/blm/stun.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Ability',
                Id                      = 556,
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                },
                Label                   = "Sneak Attack",
                Image                   = "abilities2/thf/SA.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Ability',
                Id                      = 562,
                Macro                   = T{
                    "/ja \"Arcane Circle\" <me>",
                },
                Label                   = "Arcane Circle",
                Image                   = "abilities2/drk/arcane.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 561,
                Macro                   = T{
                    "/ja \"Souleater\" <me>",
                },
                Label                   = "Souleater",
                Image                   = "abilities2/drk/souleater.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 535,
                Macro                   = T{
                    "/ja \"Blood Weapon\" <me>",
                },
                Label                   = "Blood Weapon",
                Image                   = "abilities2/drk/bw.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 563,
                Macro                   = T{
                    "/ja \"Last Resort\" <me>",
                },
                Label                   = "Last Resort",
                Image                   = "abilities2/drk/lr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["6"] = {
                ActionType              = 'Ability',
                Id                      = 589,
                Macro                   = T{
                    "/ja \"Weapon Bash\" <t>",
                },
                Label                   = "Weapon Bash",
                Image                   = "abilities2/drk/wb.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!9"] = {
                ActionType              = 'Item',
                Id                      = 4165,
                Macro                   = T{
                    "/item \"Silent Oil\" <me>",
                },
                Label                   = "Silent Oil",
                Image                   = "ITEM:4165",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 245,
                Macro                   = T{
                    "/ma \"Drain\" <t>",
                },
                Label                   = "Drain",
                Image                   = "spells2/blm/drain.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};