return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["1"] = {
                ActionType              = 'Spell',
                Id                      = 1,
                Macro                   = T{
                    "/ma \"Cure\" <t>",
                },
                Label                   = "Cure",
                Image                   = "spells/1.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["9"] = {
                ActionType              = 'Item',
                Id                      = 4394,
                Macro                   = T{
                    "/item \"Ginger Cookie\" <me>",
                },
                Label                   = "Ginger Cookie",
                Image                   = "ITEM:4394",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells/23.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 230,
                Macro                   = T{
                    "/ma \"Bio\" <t>",
                },
                Label                   = "Bio",
                Image                   = "spells/230.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 532,
                Macro                   = T{
                    "/ja \"Chainspell\" <me>",
                },
                Label                   = "Chainspell",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities/69.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!5"] = {
                ActionType              = 'Spell',
                Id                      = 254,
                Macro                   = T{
                    "/ma \"Blind\" <t>",
                },
                Label                   = "Blind",
                Image                   = "spells/254.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!3"] = {
                ActionType              = 'Spell',
                Id                      = 56,
                Macro                   = T{
                    "/ma \"Slow\" <t>",
                },
                Label                   = "Slow",
                Image                   = "spells/56.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!4"] = {
                ActionType              = 'Spell',
                Id                      = 58,
                Macro                   = T{
                    "/ma \"Paralyze\" <t>",
                },
                Label                   = "Paralyze",
                Image                   = "spells/58.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};