return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Spell',
                Id                      = 109,
                Macro                   = T{
                    "/ma \"Refresh\" <t>",
                },
                Label                   = "Refresh",
                Image                   = "spells2/rdm/refresh.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^7"] = {
                ActionType              = 'Spell',
                Id                      = 216,
                Macro                   = T{
                    "/ma \"Gravity\" <t>",
                },
                Label                   = "Gravity",
                Image                   = "spells2/rdm/grav.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["5"] = {
                ActionType              = 'Spell',
                Id                      = 108,
                Macro                   = T{
                    "/ma \"Regen\" <t>",
                },
                Label                   = "Regen",
                Image                   = "spells2/whm/regen.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^8"] = {
                ActionType              = 'Spell',
                Id                      = 59,
                Macro                   = T{
                    "/ma \"Silence\" <t>",
                },
                Label                   = "Silence",
                Image                   = "spells2/whm/silence.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!6"] = {
                ActionType              = 'Spell',
                Id                      = 53,
                Macro                   = T{
                    "/ma \"Blink\" <me>",
                },
                Label                   = "Blink",
                Image                   = "spells2/whm/blink.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!4"] = {
                ActionType              = 'Spell',
                Id                      = 156,
                Macro                   = T{
                    "/ma \"Aero III\" <t>",
                },
                Label                   = "Aero III",
                Image                   = "spells2/blm/aero.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Spell',
                Id                      = 258,
                Macro                   = T{
                    "/ma \"Bind\" <t>",
                },
                Label                   = "Bind",
                Image                   = "spells2/blm/bind.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^5"] = {
                ActionType              = 'Spell',
                Id                      = 254,
                Macro                   = T{
                    "/ma \"Blind\" <t>",
                },
                Label                   = "Blind",
                Image                   = "spells2/blm/blind.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["7"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells2/nin/ichi.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 532,
                Macro                   = T{
                    "/ja \"Chainspell\" <me>",
                },
                Label                   = "Chainspell",
                Image                   = "abilities2/rdm/cs.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Spell',
                Id                      = 4,
                Macro                   = T{
                    "/ma \"Cure IV\" <t>",
                },
                Label                   = "Cure IV",
                Image                   = "spells2/whm/cure_III.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!7"] = {
                ActionType              = 'Spell',
                Id                      = 260,
                Macro                   = T{
                    "/ma \"Dispel\" <bt>",
                },
                Label                   = "Dispel",
                Image                   = "spells2/rdm/dispell.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 24,
                Macro                   = T{
                    "/ma \"Dia II\" <t>",
                },
                Label                   = "Dia II",
                Image                   = "spells2/whm/dia.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 231,
                Macro                   = T{
                    "/ma \"Bio II\" <t>",
                },
                Label                   = "Bio II",
                Image                   = "spells2/blm/bio.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!9"] = {
                ActionType              = 'Spell',
                Id                      = 259,
                Macro                   = T{
                    "/ma \"Sleep II\" <t>",
                },
                Label                   = "Sleep II",
                Image                   = "spells2/blm/sleep2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Spell',
                Id                      = 3,
                Macro                   = T{
                    "/ma \"Cure III\" <t>",
                },
                Label                   = "Cure III",
                Image                   = "spells2/whm/cure.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 166,
                Macro                   = T{
                    "/ma \"Thunder III\" <t>",
                },
                Label                   = "Thunder III",
                Image                   = "spells2/blm/thunder.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/echo DONE",
                },
                Label                   = "Synth",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Spell',
                Id                      = 56,
                Macro                   = T{
                    "/ma \"Slow\" <t>",
                },
                Label                   = "Slow",
                Image                   = "spells2/whm/slo.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!5"] = {
                ActionType              = 'Spell',
                Id                      = 54,
                Macro                   = T{
                    "/ma \"Stoneskin\" <me>",
                },
                Label                   = "Stoneskin",
                Image                   = "spells2/whm/stone.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["6"] = {
                ActionType              = 'Spell',
                Id                      = 143,
                Macro                   = T{
                    "/ma \"Erase\" <t>",
                },
                Label                   = "Erase",
                Image                   = "spells2/whm/erase.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^4"] = {
                ActionType              = 'Spell',
                Id                      = 58,
                Macro                   = T{
                    "/ma \"Paralyze\" <t>",
                },
                Label                   = "Paralyze",
                Image                   = "spells2/whm/para.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 151,
                Macro                   = T{
                    "/ma \"Blizzard III\" <t>",
                },
                Label                   = "Blizzard III",
                Image                   = "spells2/blm/bliz.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Spell',
                Id                      = 57,
                Macro                   = T{
                    "/ma \"Haste\" <t>",
                },
                Label                   = "Haste",
                Image                   = "spells2/whm/haste.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Ability',
                Id                      = 595,
                Macro                   = T{
                    "/ja \"Convert\" <me>",
                },
                Label                   = "Convert",
                Image                   = "abilities2/rdm/convert.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!8"] = {
                ActionType              = 'Spell',
                Id                      = 253,
                Macro                   = T{
                    "/ma \"Sleep\" <t>",
                },
                Label                   = "Sleep",
                Image                   = "spells2/blm/sleep.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["0"] = {
                ActionType              = 'Spell',
                Id                      = 159,
                Macro                   = T{
                    "/ma \"Stone\" <t>",
                },
                Label                   = "Stone",
                Image                   = "spells/159.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!3"] = {
                ActionType              = 'Spell',
                Id                      = 146,
                Macro                   = T{
                    "/ma \"Fire III\" <t>",
                },
                Label                   = "Fire III",
                Image                   = "spells2/blm/fire.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^6"] = {
                ActionType              = 'Spell',
                Id                      = 220,
                Macro                   = T{
                    "/ma \"Poison\" <bt>",
                },
                Label                   = "Poison",
                Image                   = "spells2/blm/poison.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};