return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Ability',
                Id                      = 574,
                Macro                   = T{
                    "/ja \"Third Eye\" <me>",
                },
                Label                   = "Third Eye",
                Image                   = "abilities2/sam/thirdeye.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells/353.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ra <t>",
                    "/p Pulling <t>",
                },
                Label                   = "Range",
                Image                   = "misc/bow.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Ability',
                Id                      = 547,
                Macro                   = T{
                    "/ja \"Provoke\" <t>",
                },
                Label                   = "Provoke",
                Image                   = "abilities2/war/provoke.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 685,
                Macro                   = T{
                    "/ja \"Hasso\" <me>",
                },
                Label                   = "Hasso",
                Image                   = "abilities2/sam/hasso.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 539,
                Macro                   = T{
                    "/ja \"Meikyo Shisui\" <me>",
                },
                Label                   = "Shisui",
                Image                   = "abilities2/sam/meikyo_shisui.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 575,
                Macro                   = T{
                    "/ja \"Meditate\" <me>",
                },
                Label                   = "Meditate",
                Image                   = "abilities2/sam/meditate.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 144,
                Macro                   = T{
                    "/ws \"Tachi: Enpi\" <t>",
                },
                Label                   = "Tachi: Enpi",
                Image                   = "ITEM:17829",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["^1"] = {
                ActionType              = 'Ability',
                Id                      = 543,
                Macro                   = T{
                    "/ja \"Berserk\" <me>",
                },
                Label                   = "Berserk",
                Image                   = "abilities2/war/berserk.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};