return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Ability',
                Id                      = 602,
                Macro                   = T{
                    "/ja \"Release\" <me>",
                },
                Label                   = "Release",
                Image                   = "spells2/smn/release.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!9"] = {
                ActionType              = 'Spell',
                Id                      = 297,
                Macro                   = T{
                    "/ma \"Fenrir\" <me>",
                },
                Label                   = "Fenrir",
                Image                   = "spells2/smn/fenrir.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["5"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/echo Closing BP in 3",
                    "/wait 3",
                    "/ja \"Burning Strike\" <t>",
                    "/wait 2",
                    "/p Closing Fusion on <t>",
                },
                Label                   = "SC Close",
                Image                   = "misc/sc.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!5"] = {
                ActionType              = 'Spell',
                Id                      = 299,
                Macro                   = T{
                    "/ma \"Titan\" <me>",
                },
                Label                   = "Titan",
                Image                   = "spells2/smn/titan.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!6"] = {
                ActionType              = 'Spell',
                Id                      = 303,
                Macro                   = T{
                    "/ma \"Ramuh\" <me>",
                },
                Label                   = "Ramuh",
                Image                   = "spells2/smn/ramuh.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/echo DONE!!!",
                },
                Label                   = "Synth",
                Image                   = "misc/synth.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!7"] = {
                ActionType              = 'Spell',
                Id                      = 302,
                Macro                   = T{
                    "/ma \"Shiva\" <me>",
                },
                Label                   = "Shiva",
                Image                   = "spells2/smn/shiva.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^5"] = {
                ActionType              = 'Ability',
                Id                      = 684,
                Macro                   = T{
                    "/ja \"Whispering Wind\" <me>",
                    "/ja \"Healing Ruby\" <t>",
                },
                Label                   = "Heals",
                Image                   = "spells2/smn/heal.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells2/whm/dia.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 294,
                Macro                   = T{
                    "/ma \"Light Spirit\" <me>",
                },
                Label                   = "Light Spirit",
                Image                   = "spells/294.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 542,
                Macro                   = T{
                    "/ja \"Astral Flow\" <me>",
                },
                Label                   = "Astral Flow",
                Image                   = "spells2/smn/astral_flow.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Ability',
                Id                      = 603,
                Macro                   = T{
                    "/ja \"Meteorite\" <t>",
                    "/ja \"Crescent Fang\" <t>",
                    "/ja \"Camisado\" <t>",
                    "/ja \"Burning Strike\" <t>",
                    "/ja \"Megalith Throw\" <t>",
                    "/ja \"Tail Whip\" <t>",
                    "/ja \"Claw\" <t>",
                    "/ja \"Shock Strike\" <t>",
                    "/ja \"Double Slap\" <t>",
                },
                Label                   = "Rage",
                Image                   = "spells2/smn/rage.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Ability',
                Id                      = 600,
                Macro                   = T{
                    "/ja \"Assault\" <t>",
                },
                Label                   = "Assault",
                Image                   = "spells2/smn/assault.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["9"] = {
                ActionType              = 'Item',
                Id                      = 4394,
                Macro                   = T{
                    "/item \"Ginger Cookie\" <me>",
                },
                Label                   = "Ginger Cookie",
                Image                   = "ITEM:4394",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Ability',
                Id                      = 603,
                Macro                   = T{
                    "/ja \"Aero II\" <t>",
                    "/ja \"Fire II\" <t>",
                    "/ja \"Water II\" <t>",
                    "/ja \"Stone II\" <t>",
                    "/ja \"Thunder II\" <t>",
                    "/ja \"Blizzard II\" <t>",
                },
                Label                   = "Spell",
                Image                   = "spells2/smn/spell.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Spell',
                Id                      = 108,
                Macro                   = T{
                    "/ma \"Regen\" <t>",
                },
                Label                   = "Regen",
                Image                   = "spells2/whm/regen.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!1"] = {
                ActionType              = 'Spell',
                Id                      = 296,
                Macro                   = T{
                    "/ma \"Carbuncle\" <me>",
                },
                Label                   = "Carbuncle",
                Image                   = "spells2/smn/carbuncle.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^4"] = {
                ActionType              = 'Ability',
                Id                      = 684,
                Macro                   = T{
                    "/ja \"Shining Ruby\" <me>",
                    "/ja \"Somnolence\" <t>",
                    "/ja \"Ecliptic Growl\" <me>",
                    "/ja \"Hastega\" <me>",
                    "/ja \"Rolling Thunder\" <me>",
                    "/ja \"Crimson Howl\" <me>",
                    "/ja \"Spring Water\" <me>",
                    "/ja \"Earthen Ward\" <me>",
                },
                Label                   = "Buffs",
                Image                   = "spells2/smn/ward.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!2"] = {
                ActionType              = 'Spell',
                Id                      = 301,
                Macro                   = T{
                    "/ma \"Garuda\" <me>",
                },
                Label                   = "Garuda",
                Image                   = "spells2/smn/garuda.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Ability',
                Id                      = 601,
                Macro                   = T{
                    "/ja \"Retreat\" <me>",
                },
                Label                   = "Retreat",
                Image                   = "spells2/smn/retreat.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["0"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ctimers add P 0 1 0 ",
                },
                Label                   = "Timer",
                Image                   = "misc/Timer.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!8"] = {
                ActionType              = 'Spell',
                Id                      = 304,
                Macro                   = T{
                    "/ma \"Diabolos\" <me>",
                },
                Label                   = "Diabolos",
                Image                   = "spells2/smn/diab.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^7"] = {
                ActionType              = 'Spell',
                Id                      = 53,
                Macro                   = T{
                    "/ma \"Blink\" <me>",
                },
                Label                   = "Blink",
                Image                   = "spells2/whm/blink.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!3"] = {
                ActionType              = 'Spell',
                Id                      = 298,
                Macro                   = T{
                    "/ma \"Ifrit\" <me>",
                },
                Label                   = "Ifrit",
                Image                   = "spells2/smn/ifrit.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!4"] = {
                ActionType              = 'Spell',
                Id                      = 300,
                Macro                   = T{
                    "/ma \"Leviathan\" <me>",
                },
                Label                   = "Leviathan",
                Image                   = "spells2/smn/levi.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};