return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["4"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells2/nin/ichi.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^6"] = {
                ActionType              = 'Ability',
                Id                      = 553,
                Macro                   = T{
                    "/ja \"Steal\" <t>",
                },
                Label                   = "Steal",
                Image                   = "abilities2/thf/steal.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["!0"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells2/nin/tonko.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^1"] = {
                ActionType              = 'Ability',
                Id                      = 556,
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                },
                Label                   = "Sneak Attack",
                Image                   = "abilities2/thf/sa.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^2"] = {
                ActionType              = 'Ability',
                Id                      = 588,
                Macro                   = T{
                    "/ja \"Trick Attack\" <me>",
                },
                Label                   = "Trick Attack",
                Image                   = "abilities2/thf/ta.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^3"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                    "/wait 1",
                    "/ja \"Trick Attack\" <me>",
                },
                Label                   = "SATA",
                Image                   = "abilities2/thf/sata.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 16,
                Macro                   = T{
                    "/ws \"Wasp Sting\" <t>",
                },
                Label                   = "Wasp Sting",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["!1"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                    "/wait 1",
                    "/ja \"Trick Attack\" <me>",
                    "/wait 1",
                    "/ws \"Wasp Sting\" <t>",
                },
                Label                   = "Sting",
                Image                   = "abilities2/thf/sata.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^4"] = {
                ActionType              = 'Ability',
                Id                      = 555,
                Macro                   = T{
                    "/ja \"Hide\" <me>",
                },
                Label                   = "Hide",
                Image                   = "abilities2/thf/hide.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^9"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                    "/lastsynth",
                    "/wait 23",
                },
                Label                   = "Synth",
                Image                   = "misc/synth.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["3"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ra <t>",
                },
                Label                   = "Range",
                Image                   = "misc/bow.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^0"] = {
                ActionType              = 'Ability',
                Id                      = 533,
                Macro                   = T{
                    "/ja \"Perfect Dodge\" <me>",
                },
                Label                   = "Perfect Dodge",
                Image                   = "abilities2/thf/pd.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 19,
                Macro                   = T{
                    "/ws \"Gust Slash\" <t>",
                },
                Label                   = "Gust Slash",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^7"] = {
                ActionType              = 'Ability',
                Id                      = 557,
                Macro                   = T{
                    "/ja \"Mug\" <t>",
                },
                Label                   = "Mug",
                Image                   = "abilities2/thf/mug.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["^8"] = {
                ActionType              = 'Ability',
                Id                      = 554,
                Macro                   = T{
                    "/ja \"Flee\" <me>",
                },
                Label                   = "Flee",
                Image                   = "abilities2/thf/flee.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
            ["0"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ra <t>",
                    "/p Pulling <t>",
                },
                Label                   = "Pulling",
                Image                   = "misc/throw.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = true,
            },
        } },
    },
};